In [1]:
import numpy as np
import pandas as pd

In [2]:
dates = pd.date_range("20130101", periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[us]', freq='D')

In [3]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2013-01-01 -0.098981  0.219625  1.038727  1.693904
2013-01-02 -1.780890 -0.866222 -0.325065  0.307535
2013-01-03  0.827913  0.063257 -0.304334 -0.259553
2013-01-04 -0.649143  0.244203  0.607717 -0.311612
2013-01-05 -0.239163 -1.141549  1.175380 -0.625069
2013-01-06  0.588118  0.005483 -0.219535 -0.609651

In [4]:
s1 = pd.Series(
   [1, 2, 3, 4, 5, 6],
   index=pd.date_range("20130102", periods=6))
s1

2013-01-02    1
2013-01-03    2
2013-01-04    3
2013-01-05    4
2013-01-06    5
2013-01-07    6
Freq: D, dtype: int64

In [5]:
df["F"] = s1
df

                   A         B         C         D    F
2013-01-01 -0.098981  0.219625  1.038727  1.693904  NaN
2013-01-02 -1.780890 -0.866222 -0.325065  0.307535  1.0
2013-01-03  0.827913  0.063257 -0.304334 -0.259553  2.0
2013-01-04 -0.649143  0.244203  0.607717 -0.311612  3.0
2013-01-05 -0.239163 -1.141549  1.175380 -0.625069  4.0
2013-01-06  0.588118  0.005483 -0.219535 -0.609651  5.0

In [6]:
list(df.columns) + ["E"]

['A', 'B', 'C', 'D', 'F', 'E']

In [7]:
["E"]

['E']

In [8]:
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ["E"])
df1

                   A         B         C         D    F   E
2013-01-01 -0.098981  0.219625  1.038727  1.693904  NaN NaN
2013-01-02 -1.780890 -0.866222 -0.325065  0.307535  1.0 NaN
2013-01-03  0.827913  0.063257 -0.304334 -0.259553  2.0 NaN
2013-01-04 -0.649143  0.244203  0.607717 -0.311612  3.0 NaN

In [9]:
df = pd.DataFrame(
    {"id": [1, 2, 3, 4, 5, 6], "raw_grade": ["a", "b", "b", "a", "a", "e"]}
)
df

   id raw_grade
0   1         a
1   2         b
2   3         b
3   4         a
4   5         a
5   6         e

In [10]:
df["grade"] = df["raw_grade"].astype("category")
df["grade"]

0    a
1    b
2    b
3    a
4    a
5    e
Name: grade, dtype: category
Categories (3, str): ['a', 'b', 'e']

In [11]:
new_categories = ["very good", "good", "very bad"]
df["grade"] = df["grade"].cat.rename_categories(new_categories)
df

   id raw_grade      grade
0   1         a  very good
1   2         b       good
2   3         b       good
3   4         a  very good
4   5         a  very good
5   6         e   very bad

In [12]:
df["grade"] = df["grade"].cat.set_categories(
    ["very bad", "bad", "medium", "good", "very good"]
)

In [13]:
df["grade"]

0    very good
1         good
2         good
3    very good
4    very good
5     very bad
Name: grade, dtype: category
Categories (5, str): ['very bad', 'bad', 'medium', 'good', 'very good']

In [14]:
index = pd.date_range("1/1/2014",periods=1000)
df = pd.DataFrame(
    np.random.randn(1000, 4), index=index, columns=["A", "B", "C", "D"]
)
df

                   A         B         C         D
2014-01-01  0.526829  0.940479 -0.282804 -0.146498
2014-01-02  0.930926  0.303549 -1.642713  0.443260
2014-01-03  0.465392 -1.269841  0.685612  0.965017
2014-01-04 -1.387051  1.625182  0.407340 -1.100289
2014-01-05  0.449477 -0.683281 -1.222970 -0.023057
...              ...       ...       ...       ...
2016-09-22  0.701151  0.693382  0.643863  0.946839
2016-09-23 -0.739782 -0.875650  0.382705 -1.752968
2016-09-24  1.423768  0.037154 -1.865466  1.010098
2016-09-25  1.348964  0.258532  0.203233 -0.424623
2016-09-26  1.447140  0.613136 -0.515788 -1.322168

[1000 rows x 4 columns]

In [15]:
df = df.cumsum()
df

                    A          B           C          D
2014-01-01   0.526829   0.940479   -0.282804  -0.146498
2014-01-02   1.457755   1.244028   -1.925517   0.296762
2014-01-03   1.923147  -0.025814   -1.239905   1.261779
2014-01-04   0.536096   1.599368   -0.832565   0.161490
2014-01-05   0.985573   0.916087   -2.055536   0.138433
...               ...        ...         ...        ...
2016-09-22 -12.983427 -15.843557  104.693458  48.079013
2016-09-23 -13.723208 -16.719207  105.076163  46.326045
2016-09-24 -12.299440 -16.682053  103.210697  47.336143
2016-09-25 -10.950477 -16.423521  103.413929  46.911520
2016-09-26  -9.503337 -15.810385  102.898141  45.589352

[1000 rows x 4 columns]

In [16]:
s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])
s

a    1.467241
b   -0.109622
c   -1.389883
d   -0.618969
e   -0.720977
dtype: float64

In [17]:
(s.iloc[1:] + s.iloc[:-1]).dropna()

b   -0.219243
c   -2.779767
d   -1.237939
dtype: float64

In [18]:
s.iloc[:-1]

a    1.467241
b   -0.109622
c   -1.389883
d   -0.618969
dtype: float64

In [19]:
np.random.rand(4) * 3

array([0.86316887, 1.57726977, 1.69085743, 2.37951692])

In [20]:
[3] + [4]

[3, 4]

In [21]:
df.insert

<bound method DataFrame.insert of                     A          B           C          D
2014-01-01   0.526829   0.940479   -0.282804  -0.146498
2014-01-02   1.457755   1.244028   -1.925517   0.296762
2014-01-03   1.923147  -0.025814   -1.239905   1.261779
2014-01-04   0.536096   1.599368   -0.832565   0.161490
2014-01-05   0.985573   0.916087   -2.055536   0.138433
...               ...        ...         ...        ...
2016-09-22 -12.983427 -15.843557  104.693458  48.079013
2016-09-23 -13.723208 -16.719207  105.076163  46.326045
2016-09-24 -12.299440 -16.682053  103.210697  47.336143
2016-09-25 -10.950477 -16.423521  103.413929  46.911520
2016-09-26  -9.503337 -15.810385  102.898141  45.589352

[1000 rows x 4 columns]>

In [22]:
df.ne()

TypeError: DataFrame.ne() missing 1 required positional argument: 'other'

In [23]:
df = pd.DataFrame(np.random.randn(4,3), index = list('abcd'), columns=['one','two','three'])
df

        one       two     three
a  1.683755 -0.414664  1.059151
b  1.526633 -0.663630 -0.402199
c -0.534712  0.798390  0.584691
d -1.098923  1.118949  0.255081

In [24]:
df.loc['a','three'] = np.nan
df.loc['d','one'] = np.nan
df

        one       two     three
a  1.683755 -0.414664       NaN
b  1.526633 -0.663630 -0.402199
c -0.534712  0.798390  0.584691
d       NaN  1.118949  0.255081

In [25]:
ts_stand = (df - df.mean()) / df.std()
ts_stand

        one       two     three
a  0.639646 -0.709174       NaN
b  0.512727 -0.991930 -1.090814
c -1.152373  0.668519  0.873423
d       NaN  1.032584  0.217391

In [26]:
df.mean()

one      0.891892
two      0.209761
three    0.145858
dtype: float64

In [27]:
df.std()

one      1.237970
two      0.880497
three    0.502430
dtype: float64

In [28]:
array = [1,2,3,np.nan]
np.mean(array)

np.float64(nan)

In [31]:
arr = np.random.randn(5)
print(arr)
factor = pd.cut(arr, 4)
factor

[-0.44148777  0.61091799 -0.3439921  -0.44458142 -0.88918556]

[(-0.514, -0.139], (0.236, 0.611], (-0.514, -0.139], (-0.514, -0.139], (-0.891, -0.514]]
Categories (4, interval[float64, right]): [(-0.891, -0.514] < (-0.514, -0.139] < (-0.139, 0.236] < (0.236, 0.611]]

In [32]:
tsdf = pd.DataFrame(
    np.random.randn(10, 3),
    columns=["A", "B", "C"],
    index=pd.date_range("1/1/2000", periods=10),
)
tsdf

                   A         B         C
2000-01-01 -0.952335 -0.329052  0.210329
2000-01-02 -0.966726  1.558624 -0.659942
2000-01-03 -0.025407 -0.175988  0.192965
2000-01-04 -0.549970 -1.836580 -0.349117
2000-01-05 -0.148925 -0.060988  0.159016
2000-01-06 -0.596727  2.112173  0.742692
2000-01-07  0.679911  0.370050 -0.916708
2000-01-08 -0.419220 -0.910092 -0.300604
2000-01-09 -0.699732  1.362192 -1.266098
2000-01-10  0.746568  1.456771  0.193702

In [33]:
tsdf.iloc[3:7] = np.nan
tsdf

                   A         B         C
2000-01-01 -0.952335 -0.329052  0.210329
2000-01-02 -0.966726  1.558624 -0.659942
2000-01-03 -0.025407 -0.175988  0.192965
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08 -0.419220 -0.910092 -0.300604
2000-01-09 -0.699732  1.362192 -1.266098
2000-01-10  0.746568  1.456771  0.193702

In [ ]:
tsdf.apply(pd.Series.interpolate)

                   A         B         C
2000-01-01 -0.952335 -0.329052  0.210329
2000-01-02 -0.966726  1.558624 -0.659942
2000-01-03 -0.025407 -0.175988  0.192965
2000-01-04 -0.104169 -0.322809  0.094251
2000-01-05 -0.182932 -0.469630 -0.004462
2000-01-06 -0.261695 -0.616451 -0.103176
2000-01-07 -0.340458 -0.763271 -0.201890
2000-01-08 -0.419220 -0.910092 -0.300604
2000-01-09 -0.699732  1.362192 -1.266098
2000-01-10  0.746568  1.456771  0.193702